version: '3.8'

services:
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=project
        ports:
          - "27017:27017"

    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
            - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
        depends_on:
            - mongo
        ports:
          - "8888:8081"

    selenium-event-bus:
        image: selenium/event-bus:4.14.1-20231020
        container_name: selenium-event-bus
        ports:
        - "4442:4442"
        - "4443:4443"
        - "5557:5557"

    selenium-sessions:
        image: selenium/sessions:4.14.1-20231020
        container_name: selenium-sessions
        ports:
        - "5556:5556"
        depends_on:
        - selenium-event-bus
        environment:
        - SE_EVENT_BUS_HOST=selenium-event-bus
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

    selenium-session-queue:
        image: selenium/session-queue:4.14.1-20231020
        container_name: selenium-session-queue
        ports:
        - "5559:5559"

    selenium-distributor:
        image: selenium/distributor:4.14.1-20231020
        container_name: selenium-distributor
        ports:
        - "5553:5553"
        depends_on:
        - selenium-event-bus
        - selenium-sessions
        - selenium-session-queue
        environment:
        - SE_EVENT_BUS_HOST=selenium-event-bus
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        - SE_SESSIONS_MAP_HOST=selenium-sessions
        - SE_SESSIONS_MAP_PORT=5556
        - SE_SESSION_QUEUE_HOST=selenium-session-queue
        - SE_SESSION_QUEUE_PORT=5559

    selenium-router:
        image: selenium/router:4.14.1-20231020
        container_name: selenium-router
        ports:
        - "4444:4444"
        depends_on:
        - selenium-distributor
        - selenium-sessions
        - selenium-session-queue
        environment:
        - SE_DISTRIBUTOR_HOST=selenium-distributor
        - SE_DISTRIBUTOR_PORT=5553
        - SE_SESSIONS_MAP_HOST=selenium-sessions
        - SE_SESSIONS_MAP_PORT=5556
        - SE_SESSION_QUEUE_HOST=selenium-session-queue
        - SE_SESSION_QUEUE_PORT=5559

    chrome:
        image: selenium/node-chrome:latest
        shm_size: 2gb
        depends_on:
        - selenium-event-bus
        environment:
        - SE_EVENT_BUS_HOST=selenium-event-bus
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443